# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-agg-kvbm
spec:
  services:
    Frontend:
      dynamoNamespace: vllm-agg-kvbm
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.5.0
    VllmDecodeWorker:
      envFromSecret: hf-token-secret
      dynamoNamespace: vllm-agg-kvbm
      componentType: worker
      replicas: 2
      resources:
        requests:
          gpu: "1"
        limits:
          gpu: "1"
      envs:
        - name: DYN_KVBM_CPU_CACHE_GB
          value: "200"
      extraPodSpec:
        volumes:
          - name: shared-models
            hostPath:
              path: /home/bedicloud/models
              type: Directory
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.5.0
          workingDir: /workspace/components/backends/vllm
          env:
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: TRANSFORMERS_OFFLINE
              value: "1"
          volumeMounts:
            - name: shared-models
              mountPath: /shared-models
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - /shared-models/DeepSeek/DeepSeek-R1-Distill-Qwen-7B
            - --connector
            - kvbm
