# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg
spec:
  services:
    Frontend:
      dynamoNamespace: vllm-disagg
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.5.0
    VllmDecodeWorker:
      dynamoNamespace: vllm-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: decode
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        volumes:
          - name: shared-models
            hostPath:
              path: /home/bedicloud/models
              type: Directory
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.5.0
          workingDir: /workspace/components/backends/vllm
          env:
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: TRANSFORMERS_OFFLINE
              value: "1"
          volumeMounts:
            - name: shared-models
              mountPath: /shared-models
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - /shared-models/DeepSeek/DeepSeek-R1-Distill-Qwen-7B
    VllmPrefillWorker:
      dynamoNamespace: vllm-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: prefill
      replicas: 2
      resources:
        limits:
          gpu: "1"
      envs:
          - name: DYN_KVBM_CPU_CACHE_GB
            value: "200"
          - name: DYN_KVBM_BARRIER_ID_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

      extraPodSpec:   
        volumes:
          - name: shared-models
            hostPath:
              path: /home/bedicloud/models
              type: Directory
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.5.0
          workingDir: /workspace/components/backends/vllm
          env:
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: TRANSFORMERS_OFFLINE
              value: "1"
          volumeMounts:
            - name: shared-models
              mountPath: /shared-models
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
            - --model
            - /shared-models/DeepSeek/DeepSeek-R1-Distill-Qwen-7B
            - --is-prefill-worker
            - --connector
            - kvbm